language: go
go:
  - "1.9"
matrix:
  include:
    - stage: test
      script: make test
    - stage: publish
      sudo: required
      services:
      - docker
      script: ./.travis.docker-push.sh
stages:
  - test
  - name: publish
    if: branch = master AND type = push
